"""Build a local fallback app icon from the project's reference artwork.

The reference image is used directly for the mascot and tuna pixels so the
icon stays faithful to the intended jellybean-character design. The shipping
icon is generated by Gemini Nano Banana; this renderer is kept as a
reproducible offline fallback and deliberately writes a separate file.
"""
from pathlib import Path
from PIL import Image, ImageChops, ImageDraw, ImageEnhance, ImageFilter
import math

ROOT = Path(__file__).resolve().parents[1]
REFERENCE = ROOT / "docs" / "Image" / "Gemini_Generated_Image_.png"
OUTPUT = ROOT / "Assets" / "Sprite" / "GameIcon_Fallback.png"
SIZE = 1024
S = 3

ref = Image.open(REFERENCE).convert("RGBA")

# Night-camp gradient background keeps the source mascot legible at icon size.
canvas = Image.new("RGBA", (SIZE * S, SIZE * S), (8, 17, 37, 255))
pix = canvas.load()
for y in range(SIZE * S):
    for x in range(SIZE * S):
        glow = max(0.0, 1.0 - math.hypot(x / (SIZE * S) - 0.48, y / (SIZE * S) - 0.68) * 1.35)
        pix[x, y] = (int(8 + 16 * glow), int(17 + 22 * glow), int(37 + 20 * glow), 255)
d = ImageDraw.Draw(canvas)

# Low-poly campfire and pine silhouettes echo the reference without competing with the mascot.
d.polygon([(0, 720*S), (120*S, 620*S), (235*S, 705*S), (335*S, 638*S), (470*S, 730*S),
           (585*S, 650*S), (720*S, 720*S), (850*S, 615*S), (1024*S, 700*S), (1024*S, 1024*S), (0, 1024*S)], fill=(18, 43, 48, 255))
for x, h in [(90, 230), (175, 285), (845, 280), (930, 235)]:
    d.polygon([(x*S, 740*S), ((x-75)*S, 740*S), ((x-18)*S, (740-h)*S), ((x+18)*S, (740-h)*S), ((x+75)*S, 740*S)], fill=(20, 55, 45, 255))
d.polygon([(350*S, 745*S), (395*S, 650*S), (440*S, 745*S)], fill=(218, 91, 28, 210))
d.polygon([(371*S, 745*S), (395*S, 685*S), (420*S, 745*S)], fill=(255, 183, 45, 230))

# Crop the green reference mascot (same shape and eyes as the supplied image).
# Enlarge it and let the lower body leave the frame so the icon reads as a
# face-led portrait rather than a full-body character.
char_crop = (390, 500, 625, 1000)
char = ref.crop(char_crop).resize((780*S, 1100*S), Image.Resampling.LANCZOS)
char_mask = Image.new("L", char.size, 0)
cm = ImageDraw.Draw(char_mask)
char_outline = [(115, 55), (255, 38), (470, 62), (625, 140), (700, 265),
                (710, 550), (670, 760), (610, 900), (510, 1030), (375, 1085),
                (270, 1010), (205, 900), (145, 745), (82, 560), (78, 280)]
cm.polygon([(x*S, y*S) for x, y in char_outline], fill=255)
char_mask = char_mask.filter(ImageFilter.GaussianBlur(1.0*S))
# Keep only the green mascot pixels from the supplied scene; this removes the
# orange fire and yellow ground that sit behind it in the reference crop.
green = Image.new("L", char.size, 0)
gp = green.load()
cp = char.convert("RGB").load()
for yy in range(char.height):
    for xx in range(char.width):
        rr, gg, bb = cp[xx, yy]
        if gg > 42 and gg > rr * 1.08 and gg > bb * 1.08:
            gp[xx, yy] = 255
green = green.filter(ImageFilter.MaxFilter(31))
char_mask = ImageChops.multiply(char_mask, green)
char_pos = (300*S, 270*S)

# A restrained drop shadow keeps the enlarged face readable over the campfire.
shadow = Image.new("RGBA", char.size, (3, 12, 26, 0))
shadow.putalpha(char_mask.filter(ImageFilter.GaussianBlur(12*S)))
canvas.alpha_composite(shadow, (char_pos[0] + 16*S, char_pos[1] + 20*S))

# Put the reference tuna behind the mascot, rising diagonally from the
# shoulder toward the upper-left. This keeps the frozen-tuna cue without
# covering the face.
fish_crop = (205, 505, 450, 785)
fish = ref.crop(fish_crop).resize((860*S, 500*S), Image.Resampling.LANCZOS)
fish = ImageEnhance.Color(fish).enhance(0.65)
fish = Image.alpha_composite(fish, Image.new("RGBA", fish.size, (67, 180, 220, 72)))
fish_mask = Image.new("L", fish.size, 0)
fm = ImageDraw.Draw(fish_mask)
fish_outline = [(45, 180), (95, 120), (190, 75), (325, 55), (505, 95),
                (650, 170), (765, 265), (835, 335), (790, 365), (670, 360),
                (500, 315), (330, 255), (180, 220), (75, 205)]
fm.polygon([(x*S, y*S) for x, y in fish_outline], fill=255)
fish_mask = fish_mask.filter(ImageFilter.GaussianBlur(1.5*S))
fish = fish.rotate(-10, expand=True, resample=Image.Resampling.BICUBIC)
fish_mask = fish_mask.rotate(-10, expand=True, resample=Image.Resampling.BICUBIC)
canvas.paste(fish, (-55*S, 80*S), fish_mask)
canvas.paste(char, char_pos, char_mask)

# The source's black oval eyes are restored on top of the composited layers so
# the tuna behind the shoulder cannot show through the reference eye cutouts.
d = ImageDraw.Draw(canvas)
d.ellipse((442*S, 472*S, 525*S, 579*S), fill=(18, 24, 29, 255))
d.ellipse((614*S, 472*S, 700*S, 579*S), fill=(18, 24, 29, 255))

# Frost facets on the exposed tuna reinforce the frozen-tuna cue.
d.polygon([(95*S, 340*S), (150*S, 285*S), (180*S, 350*S)], fill=(196, 246, 252, 230))
d.polygon([(315*S, 235*S), (370*S, 195*S), (400*S, 250*S)], fill=(170, 239, 250, 230))

# Rounded-square app frame with campfire-orange and cyan edge highlights.
d.rounded_rectangle((28*S, 28*S, 996*S, 996*S), radius=148*S, outline=(87, 221, 255, 255), width=10*S)
d.rounded_rectangle((47*S, 47*S, 977*S, 977*S), radius=132*S, outline=(236, 127, 53, 215), width=5*S)

canvas.resize((SIZE, SIZE), Image.Resampling.LANCZOS).save(OUTPUT, "PNG", optimize=True)
print(OUTPUT)
